### ISSUE TITLE
Two issues ... 

### ISSUE THREAD

**Issue by nzampella** [KI7MT/jtsdk-dotnet-core#2] opened 2018-07-29 18:12 UTC
Hi Greg,

1.  I thought I updated MSYS2 as the pacman command ran twice, and on the third time, no updates needed.   I also thought I updated the JTSDK-Tools properly, but it reads 3.0.0.    Hamlib built fine.

2.  Well, I then figured I may as well try to build WJST-X 1.9.x  .. the build went fine until

[ 94%] Built target msk144d2
D:/JTSDK-Tools/tools/hamlib/qt/5.5/lib/libhamlib.a(si570avrusb.o):(.text$si570xx
xusb_set_ptt+0x7f): undefined reference to `libusb_control_transfer@32'
D:/JTSDK-Tools/tools/hamlib/qt/5.5/lib/libhamlib.a(si570avrusb.o):(.text$si570xx
xusb_set_ptt+0x97): undefined reference to `libusb_error_name@4'
D:/JTSDK-Tools/tools/Qt/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/
../../../../i686-w64-mingw32/bin/ld.exe: D:/JTSDK-Tools/tools/hamlib/qt/5.5/lib/
libhamlib.a(si570avrusb.o): bad reloc address 0x97 in section `.text$si570xxxusb
_set_ptt'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\wsjtx.dir\build.make:1073: recipe for target 'wsjtx.exe' failed
mingw32-make.exe[2]: *** [wsjtx.exe] Error 1
CMakeFiles\Makefile2:955: recipe for target 'CMakeFiles/wsjtx.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/wsjtx.dir/all] Error 2
makefile:148: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

--------------------------------------------
 CMAKE BUILD ERROR
--------------------------------------------

 There was a problem building ( devel )

 Check the screen for error messages, correct, then try to
 re-build ( jtbuild-cmd devel Release install )

====================================

So I figure a lot has to do with the fact that it may not be updated to 3.0.1 ??

Thanks in advance,

Neil, KN3ILZ

**Comment by KI7MT** [comment] 2018-07-30 09:59
Hi Neil,

I ran into this as well. It's fixed in the development branch.

Try the following:

``` shell
# Change directories to your source checkout
cd /d (C|D):\JTSDK-Tools\src\jtsdk-dotnet-core

# checkout development branch
git checkout development

# Clean
make clean

# Install
make install

# Close then, re-open JTSDK-Tools Env
```
>NOTE: You may need to do an additional `git pull` once you check out development.

After the update, you will need to rebuild Hamlib, and then, rebuid WSJT-X. Note, there are a number shortcut changes being made in the development branch. I be the correct command is still:

``` shell
jtbuild-cm rinstall
```

Let me know if you are able to compile both Hamlib, and then WSJT-X.

73's
Greg, KI7MT

**Comment by KI7MT** [comment] 2018-07-30 11:59
Hi Neil,

Just FYI. While looking at the problem you described, I ran into another bug (two actually) dealing with configuration options and sh in MSYS2. I believe both are resolved now, as I was able to build from both Hamlib and WSJT-X from new checkouts.

Let me know if you're still having trouble.

73's
Greg, KI7MT

**Comment by nzampella** [comment] 2018-07-30 15:04
Greg,

updated everything, Hamlib3 built fine, went to run jtbuild-cm with the 
rinstall option, and got an error :

" 'cat' is not recognized as an internal or external command, operable 
program, or batch file"

I'm thinking a path issue, but I can't figure out where!!

Thanks,

Neil, KN3ILZ

**Comment by KI7MT** [comment] 2018-07-30 18:25
Hi Neil,

Use jtconfig to enable unix tools:

`jtconfig -e default`  followed by `jtconfig -l` to verify what is set. Then restart the JTSDK-Tools env.

73's
Greg, KI7MT

**Comment by KI7MT** [comment] 2018-07-31 00:37
Hi Neil,

I just posted a full (start to finish) build message at [JTSDK@Groups.io](https://groups.io/g/JTSDK/message/435). If you follow those steps, and the build still fails, we'll need to investigate further.

73's
Greg, KI7MT

**Comment by nzampella** [comment] 2018-07-31 04:39
Greg,

I'm getting an error where the build-hamlib.sh script can't find the 
bookstrap file.    I suspect an error somewhere in the directory tree .. 
I don't know if the ticket system allows attachments, but I've attached 
a screen capture of the directory tree.

I'm going to get back to this tomorrow, as its 00:37 EDT.

Thanks for the help,

Neil, KN3ILZ

**Comment by KI7MT** [comment] 2018-08-01 00:52
Hi Neil,

I can't reproduce this error. I performed a complete reinstall of all Core Apps, which includes the build-hamlib.sh script.

Bootstrap, in the case of Hamlib, is a script contained within it's own repository. If the build script cannot find it, there is a only a few possible reasons for that:
- The build script is not going to the correct directory before trying to run bootstrap.
- The checkout is incomplete, or possibly, the name of the file has changed.
- You are not using the "development branch" version of the build-hamlib.sh script.

Id start with checking the development branch first. Are you sure you are using the development branch before running make install?

73's
Greg, KI7MT

**Comment by nzampella** [comment] 2018-08-01 04:11
Hi Greg,

I went over the list of steps in that post on the Groups.io list, and I 
noticed that some of the tools directories were deleted, and I followed 
those instructions, and proceeded to the next part.

I ran the build-hamlib.sh and noticed that it reflected an error that it 
could not find the libtool.    That triggered something, so I 
reinstalled the core-tools from the installer, made sure that 
asciidoctor was properly setup, then went back to the list of steps and 
verified that git had me in development.

Proceeded to run the build-hamlib.sh again, and it ran to its conclusion.

Proceeded to run jtbuild-cm rinstall.  First time through, built the 
'build.txt' file.   I then downloaded the wsjt-x source, and ran it 
again, this time all was well.  I then fired up the rig, clicked on the 
executable, it kicked off find, decoded fine.
So .. right now, all is good :)   Thanks!


73,

Neil, KN3ILZ

**Comment by KI7MT** [comment] 2018-08-01 05:11
Hi Neil,

OK, a libtool error would indicate a problem in setting up MSYS2 Hamlib package Dependencies.

Originally, I had the package list in a separate file. However, the posix nature of MSYS2 was causing issues with end of line characters. As a result, I just hard-coded the few dependencies that Hamlib requires into an install script ``install-pkg-list.sh``

If I've not made it clear in the docs to use that script during the MSYS2 Installation and Setup section, I will update it for the v3.0.2 release.

73's
Greg, KI7MT

**Closed by KI7MT** 2018-08-01 05:11 UTC
